"""
Pydantic v2 request/response schemas for the diet plan API.
"""

from __future__ import annotations

import html
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


# ── Request Schemas ──────────────────────────────────────────────────────────

_ALLOWED_CUISINES = {
    "indian", "south_indian", "north_indian", "gujarati",
    "maharashtrian", "bengali", "punjabi", "kerala",
    "mediterranean", "continental", "mixed",
}


class CreateSessionRequest(BaseModel):
    """Sent by frontend when patient clicks 'Generate Diet Plan'."""

    dietary_preferences: Optional[List[str]] = Field(
        default=[],
        max_length=10,
        description="Patient's dietary preferences and restrictions",
    )
    meal_count_preference: Optional[int] = Field(
        default=5, ge=3, le=7,
        description="Number of meals per day (3-7)",
    )
    language_preference: Optional[str] = Field(
        default="english",
        description="Language for diet plan",
    )
    cuisine_preference: Optional[str] = Field(
        default="indian",
        description="Cuisine style. Defaults to Indian.",
    )
    regional_preference: Optional[str] = Field(
        default=None,
        description=(
            "Regional Indian cuisine preference. "
            "Options: north_indian, south_indian, gujarati, "
            "maharashtrian, bengali, punjabi, kerala. "
            "If not set, a balanced mix of commonly available "
            "Indian foods is used."
        ),
    )

    @field_validator("dietary_preferences")
    @classmethod
    def sanitise_and_limit_preferences(cls, v):
        cleaned = []
        for pref in (v or []):
            clean = re.sub(r"<[^>]+>", "", str(pref))
            clean = html.unescape(clean).replace("<", "").replace(">", "").strip()
            if clean:
                cleaned.append(clean[:200])
        return cleaned[:10]

    @field_validator("cuisine_preference")
    @classmethod
    def validate_cuisine(cls, v):
        if v and v.lower() not in _ALLOWED_CUISINES:
            return "indian"
        return v.lower() if v else "indian"


class ChatMessageRequest(BaseModel):
    """Sent for each subsequent chat message after the plan is generated."""

    message: str = Field(..., min_length=1, max_length=2000)


# ── Response Schemas ─────────────────────────────────────────────────────────


class MealItem(BaseModel):
    food: str
    quantity: str
    unit: Optional[str] = None
    notes: Optional[str] = None


class MealSlot(BaseModel):
    time: str
    meal_name: str
    items: List[MealItem]
    total_calories_approx: Optional[int] = None
    medical_rationale: str
    warnings: List[str] = []


class DietPlan(BaseModel):
    plan_id: str
    patient_name: str
    generated_for_conditions: List[str] = []
    meals: List[MealSlot] = []
    general_guidelines: List[str] = []
    foods_to_avoid: List[str] = []
    hydration_notes: str = ""
    disclaimer: str = (
        "This diet plan is generated by an AI assistant using your hospital records. "
        "It is not a substitute for advice from a registered dietitian or your treating "
        "physician. Please consult your doctor before making significant dietary changes."
    )
    generated_by_provider: str = ""


class SessionResponse(BaseModel):
    session_id: str
    status: str
    diet_plan: Optional[Dict[str, Any]] = None
    current_provider: str
    message_count: int
    created_at: datetime


class SessionListItem(BaseModel):
    session_id: str
    status: str
    current_provider: str
    message_count: int
    created_at: datetime
    updated_at: datetime


class SessionListResponse(BaseModel):
    sessions: List[SessionListItem]
    total: int


class ChatResponse(BaseModel):
    session_id: str
    message_id: str
    role: str = "assistant"
    content: str
    diet_plan: Optional[Dict[str, Any]] = None
    provider_used: str
    provider_switched: bool = False
    previous_provider: Optional[str] = None


class MessageItem(BaseModel):
    message_id: str
    role: str
    content: str
    provider_used: Optional[str] = None
    is_diet_plan: bool = False
    created_at: datetime


class MessageListResponse(BaseModel):
    session_id: str
    messages: List[MessageItem]
    total: int
    has_more: bool


class HealthResponse(BaseModel):
    status: str
    service: str


class ProviderStatus(BaseModel):
    name: str
    model: str
    status: str


class ProvidersResponse(BaseModel):
    providers: list
    active_provider: Optional[str] = None
    fallback_chain: List[str] = []
